                               Numpy Important Functions

In [82]:
import numpy as np

In [81]:
#Array creation using tuple

array = np.array([10,20,30,40,50])
print("Array elements are:",array)
print("Array shape is:", array.shape)
print("Array dimension is:", array.ndim)
print("Array is of type:", array.dtype)

Array elements are: [10 20 30 40 50]
Array shape is: (5,)
Array dimension is: 1
Array is of type: int32


In [11]:
#array creation using set

array = np.array((10,20,30,40,50))
print("Array elements are:",array)
print("Array shape is:", array.shape)
print("Array dimension is:", array.ndim)
print("Array is of type:", array.dtype)

Array elements are: [10 20 30 40 50]
Array shape is: (5,)
Array dimension is: 1
Array is of type: int32


In [19]:
array = np.array([1,2,3,4,5], dtype = "i")
print("Array elements are:",array)
print("Array shape is:", array.shape)
print("Array dimension is:", array.ndim)
print("Array is of type:", array.dtype)

Array elements are: [1 2 3 4 5]
Array shape is: (5,)
Array dimension is: 1
Array is of type: int32


In [20]:
array = np.array([1,2,3,4,5], dtype = "f")
print("Array elements are:",array)
print("Array shape is:", array.shape)
print("Array dimension is:", array.ndim)
print("Array is of type:", array.dtype)

Array elements are: [1. 2. 3. 4. 5.]
Array shape is: (5,)
Array dimension is: 1
Array is of type: float32


In [21]:
array = np.array([1,2,3,4,5], dtype = "complex")
print("Array elements are:",array)
print("Array shape is:", array.shape)
print("Array dimension is:", array.ndim)
print("Array is of type:", array.dtype)

Array elements are: [1.+0.j 2.+0.j 3.+0.j 4.+0.j 5.+0.j]
Array shape is: (5,)
Array dimension is: 1
Array is of type: complex128


In [22]:
array = np.linspace(0, 50, 10, dtype = "f")
print("Array elements are:",array)
print("Array shape is:", array.shape)
print("Array dimension is:", array.ndim)
print("Array is of type:", array.dtype)

Array elements are: [ 0.         5.5555553 11.111111  16.666666  22.222221  27.777779
 33.333332  38.88889   44.444443  50.       ]
Array shape is: (10,)
Array dimension is: 1
Array is of type: float32


In [23]:
array = np.linspace(0, 50, 10, dtype = "i")
print("Array elements are:",array)
print("Array shape is:", array.shape)
print("Array dimension is:", array.ndim)
print("Array is of type:", array.dtype)

Array elements are: [ 0  5 11 16 22 27 33 38 44 50]
Array shape is: (10,)
Array dimension is: 1
Array is of type: int32


In [24]:
array = np.linspace(0, 50, 10, dtype = "complex")
print("Array elements are:",array)
print("Array shape is:", array.shape)
print("Array dimension is:", array.ndim)
print("Array is of type:", array.dtype)

Array elements are: [ 0.        +0.j  5.55555556+0.j 11.11111111+0.j 16.66666667+0.j
 22.22222222+0.j 27.77777778+0.j 33.33333333+0.j 38.88888889+0.j
 44.44444444+0.j 50.        +0.j]
Array shape is: (10,)
Array dimension is: 1
Array is of type: complex128


In [37]:
array = np.arange(0,20)
print("Array elements are:",array)
print("Array shape is:", array.shape)
print("Array dimension is:", array.ndim)
print("Array is of type:", array.dtype)

Array elements are: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
Array shape is: (20,)
Array dimension is: 1
Array is of type: int32


In [36]:
array = np.arange(0,100,20)
print("Array elements are:",array)
print("Array shape is:", array.shape)
print("Array dimension is:", array.ndim)
print("Array is of type:", array.dtype)

Array elements are: [ 0 20 40 60 80]
Array shape is: (5,)
Array dimension is: 1
Array is of type: int32


In [34]:
array = np.arange(0,100,20, dtype = "i")
print("Array elements are:",array)
print("Array shape is:", array.shape)
print("Array dimension is:", array.ndim)
print("Array is of type:", array.dtype)

Array elements are: [ 0 20 40 60 80]
Array shape is: (5,)
Array dimension is: 1
Array is of type: int32


In [33]:
array = np.arange(0,100,20, dtype = "f")
print("Array elements are:",array)
print("Array shape is:", array.shape)
print("Array dimension is:", array.ndim)
print("Array is of type:", array.dtype)

Array elements are: [ 0. 20. 40. 60. 80.]
Array shape is: (5,)
Array dimension is: 1
Array is of type: float32


In [32]:
array = np.arange(0,100,20, dtype = "complex")
print("Array elements are:",array)
print("Array shape is:", array.shape)
print("Array dimension is:", array.ndim)
print("Array is of type:", array.dtype)

Array elements are: [ 0.+0.j 20.+0.j 40.+0.j 60.+0.j 80.+0.j]
Array shape is: (5,)
Array dimension is: 1
Array is of type: complex128


In [41]:
array = np.random.uniform(0, 10, size=4)
print("Array elements are:",array)
print("Array shape is:", array.shape)
print("Array dimension is:", array.ndim)
print("Array is of type:", array.dtype)

Array elements are: [2.63952775 9.22293425 2.76108974 4.42802658]
Array shape is: (4,)
Array dimension is: 1
Array is of type: float64


In [42]:
array = np.random.uniform(0, 100, size=20)
print("Array elements are:",array)
print("Array shape is:", array.shape)
print("Array dimension is:", array.ndim)
print("Array is of type:", array.dtype)

Array elements are: [70.29574748 12.85621134 60.78485892 19.57713509 28.4371146  60.01725085
 96.26868885 68.31928106 93.22582111 12.68649933 37.94222246 68.04986611
  5.48180635 89.87795861 82.63619197 81.77470203 60.70277807 50.39521823
 88.94118752 65.98064651]
Array shape is: (20,)
Array dimension is: 1
Array is of type: float64


In [43]:
array = np.random.randint(0, 50, 10)
array

array([34, 41, 46, 44, 34, 48,  6, 15,  0, 28])

In [45]:
array = np.random.random(3)
array

array([0.8759459 , 0.820338  , 0.17945893])

In [52]:
array = np.logspace(0,10,base=2)
print(array)

[1.00000000e+00 1.15195282e+00 1.32699530e+00 1.52863599e+00
 1.76091654e+00 2.02849277e+00 2.33672798e+00 2.69180039e+00
 3.10082705e+00 3.57200647e+00 4.11478293e+00 4.74003581e+00
 5.46029763e+00 6.29000526e+00 7.24578931e+00 8.34680745e+00
 9.61512839e+00 1.10761743e+01 1.27592302e+01 1.46980313e+01
 1.69314386e+01 1.95042185e+01 2.24679395e+01 2.58820063e+01
 2.98148502e+01 3.43453008e+01 3.95641662e+01 4.55760529e+01
 5.25014628e+01 6.04792082e+01 6.96691946e+01 8.02556253e+01
 9.24506940e+01 1.06498838e+02 1.22681637e+02 1.41323458e+02
 1.62797956e+02 1.87535565e+02 2.16032123e+02 2.48858814e+02
 2.86673613e+02 3.30234477e+02 3.80414538e+02 4.38219601e+02
 5.04808306e+02 5.81515352e+02 6.69878251e+02 7.71668141e+02
 8.88925293e+02 1.02400000e+03]


In [50]:
array = np.zeros((2,3), dtype='i')
print(array)

[[0 0 0]
 [0 0 0]]


In [51]:
array = np.ones((2,3), dtype='i')
print(array)

[[1 1 1]
 [1 1 1]]


In [55]:
array = np.full((2,4), fill_value = 20, dtype='f')
print(array)

[[20. 20. 20. 20.]
 [20. 20. 20. 20.]]


In [57]:
array = np.identity(7, dtype='i')
print(array)

[[1 0 0 0 0 0 0]
 [0 1 0 0 0 0 0]
 [0 0 1 0 0 0 0]
 [0 0 0 1 0 0 0]
 [0 0 0 0 1 0 0]
 [0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1]]


In [69]:
array = np.array([[[10,64,79,13],[81,26,81,84]],[[64,76,61,94],[70,90,4,2]],[[5,94,61,49],[81,31,93,71]]])
print("Array elements are:",array)
print("Array shape is:", array.shape)
print("Array dimension is:", array.ndim)
print("Array is of type:", array.dtype)


Array elements are: [[[10 64 79 13]
  [81 26 81 84]]

 [[64 76 61 94]
  [70 90  4  2]]

 [[ 5 94 61 49]
  [81 31 93 71]]]
Array shape is: (3, 2, 4)
Array dimension is: 3
Array is of type: int32


In [71]:
np.amin(array)

2

In [72]:
np.amax(array)

94

In [73]:
np.mean(array)

57.666666666666664

In [74]:
np.median(array)

67.0

In [75]:
np.unique(array)

array([ 2,  4,  5, 10, 13, 26, 31, 49, 61, 64, 70, 71, 76, 79, 81, 84, 90,
       93, 94])

In [78]:
array.shape

(3, 2, 4)

In [79]:
np.sort(array)

array([[[10, 13, 64, 79],
        [26, 81, 81, 84]],

       [[61, 64, 76, 94],
        [ 2,  4, 70, 90]],

       [[ 5, 49, 61, 94],
        [31, 71, 81, 93]]])