# Python-Numpy

numpy:
    
    * Python package for handling N-Dimentional Array
    * It is faste than python list
    * Widely used for mathematical analsis, Matrix computations and mathematical operations
    

In [1]:
#importing required libraries

import numpy as np


In [2]:
# creating array using list
a = np.array([1,2,3,4,5,6], dtype = "i")
print(a)

[1 2 3 4 5 6]


In [4]:
#creatig array usig tuple
b = np.array((1,2,3,4,5,6), dtype = "f")
print(b)

[1. 2. 3. 4. 5. 6.]


In [5]:
# printing type of the array
print(type(a))
print(type(b))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [6]:
#Checking attriutes of array
print(a.dtype)
print(b.dtype)

int32
float32


In [7]:
aa = np.array([[1,2,3], [4,5,6]]) # 2 dimentional array
print(aa.ndim) # output 2, bcz it is a two-Dimentional array
print(aa.shape) # output 2,3 bcz it has 1 row 2 columns and 3 elements each

2
(2, 3)


In [8]:
aa = np.array([[[1,2,3], [4,5,6]], [[1,2,3],[4,5,6]]]) # 3-Dimentional array
print(aa.ndim)# output 3, bcz it is a three-Dimentional array
print(aa.shape) # output 2,2,3 bcz it has 2 row 2 columns and 3 elements each

3
(2, 2, 3)


In [9]:
#accessing elements from an array

aa[1,1,1]
aa[0,1,1]

5

In [10]:
a = np.array([[[45,55,54],[75,15,91],[70,64,25]],[[79,16,11],[17,93,56],[15,96,84]]])

In [11]:
print(a.ndim) 

3


In [12]:
print(a.shape) # 2 rows, 3 columns, 3 elements each

(2, 3, 3)


In [13]:
a[0,2,0]

70

In [14]:
type(a)

numpy.ndarray

In [15]:
a.dtype

dtype('int32')

In [16]:
a.nbytes

72

In [17]:
a = np.array([[[45,55,54],[75,15,91],[70,64,25]],[[79,16,11],[17,93,56],[15,96,84]]], dtype = complex)
print(a)
print(a.ndim)
print(a.shape)

[[[45.+0.j 55.+0.j 54.+0.j]
  [75.+0.j 15.+0.j 91.+0.j]
  [70.+0.j 64.+0.j 25.+0.j]]

 [[79.+0.j 16.+0.j 11.+0.j]
  [17.+0.j 93.+0.j 56.+0.j]
  [15.+0.j 96.+0.j 84.+0.j]]]
3
(2, 3, 3)


In [18]:
a = np.zeros((3, 4))
print(a)
print(a.ndim)
print(a.shape)
print(a.dtype)
print(a.nbytes)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
2
(3, 4)
float64
96


In [19]:
a = np.ones((3, 4), dtype = "i")
print(a)
print(a.ndim)
print(a.shape)
print(a.dtype)
print(a.nbytes)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
2
(3, 4)
int32
48


In [20]:
#numpy arange

array = np.arange(100)
print(array)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [21]:
array = np.arange(0, 10)
print(array)

[0 1 2 3 4 5 6 7 8 9]


In [22]:
array = np.arange(0, 101, 10)
print(array)

[  0  10  20  30  40  50  60  70  80  90 100]


In [23]:
# Numpy random (pernutation)

array = np.random.permutation(np.arange(10))
print(array)

[4 3 2 0 9 7 1 5 6 8]


In [24]:
#linspace function

array = np.linspace(1,5,10) # returns 10 unique values from 1 to 5
print(array)

[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


In [25]:
#numpy reshape functions

array = np.array([[1,2],[3,4], [5,6]])
print(array)

print("array shape is :",array.shape)

print("after reshape : ",array.reshape(2,3))
print("after array reshape : ",array.reshape(6,1))

[[1 2]
 [3 4]
 [5 6]]
array shape is : (3, 2)
after reshape :  [[1 2 3]
 [4 5 6]]
after array reshape :  [[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [26]:
# numpy math functions

array = np.array([[1,2],[3,4], [5,6]])
print("original array is :", array)
print()
print("min element in the array is :",array.min())
print("max element in the array is :",array.max())

print("sum is :",array.sum())
print("sum of axis 0: ", array.sum(axis=0))

sqrt = np.sqrt(array)
print("Square root of array is : ", sqrt)

std = np.std(array)
print("Standard deviatio of array is :", std)

original array is : [[1 2]
 [3 4]
 [5 6]]

min element in the array is : 1
max element in the array is : 6
sum is : 21
sum of axis 0:  [ 9 12]
Square root of array is :  [[1.         1.41421356]
 [1.73205081 2.        ]
 [2.23606798 2.44948974]]
Standard deviatio of array is : 1.707825127659933


In [27]:
# mathematical operations on two array

array1 = np.array([[1,2],[3,4]])
array2 = np.array([[1,2], [3,4]])

print("originalarray1 is:", array1)
print("original array2 is :", array2)
      
print("Addition of array1 and array2 i :", array1+array2)
print("Substraction of array1 and array2 i :", array1-array2)
print("multiplication of array1 and array2 i :", array1*array2)
print("division of array1 and array2 i :", array1/array2)

array3 = array1.dot(array2)
print("matrix product is: ",array3)

originalarray1 is: [[1 2]
 [3 4]]
original array2 is : [[1 2]
 [3 4]]
Addition of array1 and array2 i : [[2 4]
 [6 8]]
Substraction of array1 and array2 i : [[0 0]
 [0 0]]
multiplication of array1 and array2 i : [[ 1  4]
 [ 9 16]]
division of array1 and array2 i : [[1. 1.]
 [1. 1.]]
matrix product is:  [[ 7 10]
 [15 22]]


In [28]:
# Indexing in numpy array's

# one-Dimentioanl array

array = np.array([10,20,30,40,50])
print(array)
print(array.shape)
print(array.ndim)
print("original array is :",array)
print(array[:])
print(array[:2])
print(array[2:])
print(array[:-1])
print(array[-1])

[10 20 30 40 50]
(5,)
1
original array is : [10 20 30 40 50]
[10 20 30 40 50]
[10 20]
[30 40 50]
[10 20 30 40]
50


In [29]:
# two-dimentiaonal array

array = np.array([[10,20,30], [50,60,70], [80,90,100]])
print(array)
print(array.ndim)
print(array.shape)
print(array[1,2])
print(array[2,2])
print(array[0,1])

print()
print()

print(array[0:2,2])
print(array[0:1,2])



[[ 10  20  30]
 [ 50  60  70]
 [ 80  90 100]]
2
(3, 3)
70
100
20


[30 70]
[30]


In [30]:
for row in array:
    print(row)

[10 20 30]
[50 60 70]
[ 80  90 100]


In [31]:
for column in array:
    print(column)

[10 20 30]
[50 60 70]
[ 80  90 100]


In [32]:
for cell in array.flat:
    print(cell)

10
20
30
50
60
70
80
90
100


In [33]:
array1 = np.arange(6).reshape(3,2)
array2 = np.arange(6).reshape(3,2)
print(array)
print()
array = np.arange(6).reshape(2,3)
print(array)

[[ 10  20  30]
 [ 50  60  70]
 [ 80  90 100]]

[[0 1 2]
 [3 4 5]]


In [34]:
#Stacking arrays

print(np.vstack((array1, array2)))
print()
print()
print(np.hstack((array1, array2)))

[[0 1]
 [2 3]
 [4 5]
 [0 1]
 [2 3]
 [4 5]]


[[0 1 0 1]
 [2 3 2 3]
 [4 5 4 5]]


In [38]:
#indexing boolean arrays

array = np.arange(12).reshape(3,4)
print(array)

print()

array1 = array > 4
print(array1)
print()
print(array1[0:2,2])
print()



[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[False False False False]
 [False  True  True  True]
 [ True  True  True  True]]

[False  True]

